language: generic
sudo: required
services:
    docker

before_install:
  - docker build -t Ghul-A/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true Ghul-A/react-test npm test
  
after_success:
  - docker build -t Ghul-A/multi-client ./client
  - docker build -t Ghul-A/multi-nginx ./nginx
  - docker build -t Ghul-A/multi-server ./server
  - docker build -t Ghul-A/multi-worker ./worker

# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
- docker push Ghul-A/multi-client
- docker push Ghul-A/multi-nginx
- docker push Ghul-A/multi-server
- docker push Ghul-A/multi-worker 
