sudo: required
services:
    docker

before_install:
  - docker build -t ghulasghar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ghulasghar/react-test npm test
  
after_success:
  - docker build -t ghulasghar/multi-client ./client
  - docker build -t ghulasghar/multi-nginx ./nginx
  - docker build -t ghulasghar/multi-server ./server
  - docker build -t ghulasghar/multi-worker ./worker

# Log in to the docker CLI
- echo "$DOCKER_PASSWORD" |docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
- docker push ghulasghar/multi-client
- docker push ghulasghar/multi-nginx
- docker push ghulasghar/multi-server
- docker push ghulasghar/multi-worker 
